apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubewatch-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubewatch
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9581'
    spec:
      serviceAccountName: default
      volumes:
        - name: config-volume
          configMap:
            name: kubewatch-config
      containers:
      - name: kubewatch
        image: quay.io/leogr/kubewatch:dev
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /etc/kubewatch
        ports:
        - containerPort: 9581
          protocol: TCP